### ISSUE TITLE
Building on AWS F1 instance

### ISSUE THREAD

**Issue by fdb-git** [pc2/HPCC_FPGA#11]
Hello,

I'm trying to build HPCC_FPGA on AWS using an F1 instance.
I tried both with "FPGA Developer AMI (Centos 7)" and "FPGA Developer AMI (Amazon Linux 2)" with GCC 10 but during cmake execution I got some errors:

- Looking for pthread_create in pthreads - not found
- ERROR Xilinx Vitis or Intel FPGA OpenCL SDK required!

I sourced all required environment scripts so the vitis_hls command is found:
which vitis_hls
/opt/Xilinx/Vitis_HLS/2020.2/bin/vitis_hls

What OS did you use to build?

Thanks.

**Comment by Mellich** [comment]
Hi,

we test the benchmarks on CentOS 7.9, but also other OS worked in the past (i.e. XACC instances).

Does the CMake configuration find and use the correct compiler? It would be helpful if you could provide a little bit more of the output. Maybe this helps to see, where the error is located.
For the detection of Xilinx Vitis and the Intel FPGA SDK we use the find-package scripts provided by hlslib. Currently, we have defined a fixed commit of this library as an external dependency. Another idea is to update this dependency in extern/CMakeLists.txt and change line 31 from

     GIT_TAG             78124d8595baf88752fca7d2b1b7ae0e19377265)

to

      GIT_TAG             v1.2.0)

to use the latest release.

Edit: You can also use the variables VITIS_ROOT, SDX_ROOT, SDACCEL_ROOT, and XRT_ROOT to manually set the paths as described in the file: https://github.com/definelicht/hlslib/blob/master/cmake/FindVitis.cmake

**Comment by fdb-git** [comment]
Many thanks @Mellich,

I solved using GIT_TAG v1.2.0.
