### ISSUE TITLE
Supported devices

### ISSUE THREAD

**Issue by PietroGhg** [pc2/HPCC_FPGA#9]
Hello,
while trying to compile the GEMM benchmark I get the following linking error:
`INFO: [v++ 60-423]   Target device: zcu106_base
ERROR: [v++ 60-1139] Failed to parse --slr option: SLRs are not available in the specified platform.` 
Is is possible that my platform is not supported? If so, there's something that I can do about it?
Thanks

**Comment by Mellich** [comment]
Hey Pietro,

I don't know the board, but maybe it is possible to get it running by changing the compile and link settings. Currently you are using the link settings file for the u280 board (in GEMM/settings/settings.link.xilinx.gemm_cannon...). You will need to create your own link settings file and use it instead. You may copy settings.link.xilinx.gemm_cannon.ddr.generator.ini and remove the lines 8-11. There and in the settings.compile... file you can configure the compiler options to your needs. You can set the path to your new link and compile settings file using the configuration option `XILINX_LINK_SETTINGS_FILE` `XILINX_COMPILE_SETTINGS_FILE`.

I would really appreciate if you could provide your working settings here or in a pull request!

Best Regards,
Marius

**Comment by PietroGhg** [comment]
By removing line 8 i managed to compile successfully. I got this error:
`ERROR: [v++ 60-1667] Issue with .rtd file generation, Unable to extract valid SP tags information from platform`. But compilation proceeded. 
Thank you very much.

**Comment by Mellich** [comment]
You are welcome. I assume the problem is solved now.
